### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by terasakisatoshi** [AtsushiSakai/SciPy.jl#52]
TODO:

Drop support Julia 1.0
test with Julia 1.8 (1.7 if possible)

https://github.com/AtsushiSakai/SciPy.jl/blob/073706533f68989ccd761d813cd35593ea7c2a50/.github/workflows/ci.yml#L11-L14

**Comment by terasakisatoshi** [comment]
@AtsushiSakai 

Could you confirm your CircleCI account is activated?

The following warning happens

> Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.

in https://app.circleci.com/pipelines/github/AtsushiSakai/SciPy.jl/118

**Comment by AtsushiSakai** [comment]
Iet me check.
