### ISSUE TITLE
Evaling constants doesn't seem to be a good idea

### ISSUE THREAD

**Issue by SimonDanisch** [AtsushiSakai/SciPy.jl#66]
I get:
> LoadError: InitError: Evaluation into the closed module `constants` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `constants` with `eval` during precompilation - don't do this.

From: https://github.com/AtsushiSakai/SciPy.jl/blob/master/src/constants.jl#L68

I think this may just happen if you include SciPy in another package, but seems bad regardless?

Can this be done statically somehow?
I guess the easiest way would be to just print the resulting constants and then manually paste them into the package 🤷 
Not sure if one would need a more complicated solution?

**Comment by terasakisatoshi** [comment]
How do I reproduce it?

> LoadError: InitError

**Comment by SimonDanisch** [comment]
The Julia warning is pretty clear on this with the "Please DONT do this", so I think evaling constants in the `__init__`  is something that should be removed in any case ;) Does scipy change it's constants so often, that just writing them out isn't an option?
 
But here you go:
```julia
]activate --temp; add TopoPlots
using TopoPlots
```

**Comment by terasakisatoshi** [comment]
Unfortunately, I can't reproduce the error message that you have. 🤔 
Here is what I did. 

<img width="612" alt="image" src="https://user-images.githubusercontent.com/16760547/199026695-cc6f3d45-2107-4244-b877-e7a25320db86.png">

**Comment by SimonDanisch** [comment]
You didn't do what I did? This only happens if SciPy is loaded in another package ;)

**Comment by SimonDanisch** [comment]
Sorry for not providing a smaller MWE, but I don't really think it's worth the time, considering that Julia _really_ strongly suggest not to do this ;)

**Comment by AtsushiSakai** [comment]
I can reproduce it. Sorry for inconviniense.

```
~ $ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.2 (2022-09-29)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.8) pkg> activate --temp
  Activating new project at `/var/folders/fh/qhnlbtlj47x7l932htdbk6jc0000gn/T/jl_mcbmSA`

(jl_mcbmSA) pkg> add TopoPlots
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
   Installed JpegTurbo ────────────── v0.1.1
....

julia> using TopoPlots
[ Info: Precompiling TopoPlots [2bdbdf9c-dbd8-403f-947b-1a4e0dd41a7a]
ERROR: LoadError: InitError: Evaluation into the closed module `constants` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `constants` with `eval` during precompilation - don't do this.
Stacktrace:
  [1] eval
    @ ./boot.jl:368 [inlined]
  [2] __init__()
    @ SciPy.constants ~/.julia/packages/SciPy/54tSn/src/constants.jl:68
  [3] _include_from_serialized(pkg::Base.PkgId, path::String, depmods::Vector{Any})
    @ Base ./loading.jl:831
  [4] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt64)
    @ Base ./loading.jl:1039
  [5] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1315
  [6] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [7] macro expansion
    @ ./loading.jl:1180 [inlined]
  [8] macro expansion
    @ ./lock.jl:223 [inlined]
  [9] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
 [10] include
    @ ./Base.jl:419 [inlined]
 [11] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1554
 [12] top-level scope
    @ stdin:1
during initialization of module constants
in expression starting at /Users/atsushisakai/.julia/packages/TopoPlots/t7F4U/src/TopoPlots.jl:1
in expression starting at stdin:1
ERROR: Failed to precompile TopoPlots [2bdbdf9c-dbd8-403f-947b-1a4e0dd41a7a] to /Users/atsushisakai/.julia/compiled/v1.8/TopoPlots/jl_B2laYN.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:1707
 [3] compilecache
   @ ./loading.jl:1651 [inlined]
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1337
 [5] _require_prelocked(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1200
 [6] macro expansion
   @ ./loading.jl:1180 [inlined]
 [7] macro expansion
   @ ./lock.jl:223 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144
```

**Comment by terasakisatoshi** [comment]
@SimonDanisch 

> You didn't do what I did? This only happens if SciPy is loaded in another package ;)

Sorry for that. I didn't get what you meant at first. I thought you showed a pseudo module named TopoPlots, but [there exists](https://github.com/MakieOrg/TopoPlots.jl). Now I understand what you wanted to say and I can reporoduce the error you suggested as @AtsushiSakai showed above.

**Comment by terasakisatoshi** [comment]
Providing MWE, no matter how trivial, is a great way to communicate with each other. We have learned one big thing.

**Comment by SimonDanisch** [comment]
Yeah I usually try to create one, but it's always a bit annoying to create a package as part of an MWE and I wasn't 100% sure how far I will need to go to actually reproduce the issue ;)
